version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${DEV_PORT:-8888}:8888'
    volumes:
      - './work:/home/jovyan'
    command: start.sh jupyter lab --NotebookApp.token=''
